"""
paper_numbers · 论文里每一个承重数字的单一真源（round-18 新增）。

动机：本项目历史上出过多次"正文数字与 results/ 不一致"（硬编码的 prior 0.82、陈旧的
conformal r=-0.18、1004 vs 1008 特征池…）。这个脚本把正文引用的每个数字都从
results/ 的产物里现算现读并打印出来，便于逐条核对，也支撑 README 里
"every number is regenerated by the released code" 这句话。

用法：
  python src/paper_numbers.py            # 打印全部
  python src/paper_numbers.py --json     # 机器可读
"""
from __future__ import annotations
import argparse, json, math, re
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"


def hm_se(auc, n_pos, n_neg):
    auc = min(max(auc, 1e-6), 1 - 1e-6)
    q1 = auc / (2 - auc); q2 = 2 * auc * auc / (1 + auc)
    return math.sqrt(max((auc * (1 - auc) + (n_pos - 1) * (q1 - auc ** 2)
                          + (n_neg - 1) * (q2 - auc ** 2)) / (n_pos * n_neg), 1e-12))


def load_json(name):
    p = RESULTS / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()
    out = {}

    d = pd.read_csv(RESULTS / "radmlbench_sweep.csv")
    tpos = np.maximum(1, np.round(0.30 * d["minority"]).astype(int)).values
    tneg = np.maximum(1, np.round(0.30 * (d["n"] - d["minority"])).astype(int)).values
    se0 = np.array([hm_se(0.5, p, n) for p, n in zip(tpos, tneg)])

    # ---- benchmark 描述性 ----
    out["benchmark"] = {
        "n_cohorts": int(len(d)),
        "n_range": [int(d["n"].min()), int(d["n"].max())],
        "d_range": [int(d["d"].min()), int(d["d"].max())],
        "prevalence_range": [round(float((d["minority"] / d["n"]).min()), 3),
                             round(float((d["minority"] / d["n"]).max()), 3)],
        "median_n": int(d["n"].median()), "median_d": int(d["d"].median()),
        "honest_auc_range": [round(float(d["honest_pooled_auc"].min()), 2),
                             round(float(d["honest_pooled_auc"].max()), 2)],
        "median_honest_auc": round(float(d["honest_pooled_auc"].median()), 2),
        "mean_delta_split": round(float(d["delta_selection"].mean()), 3),
        "mean_delta_tuning": round(float(d["delta_tuning"].mean()), 3),
        "mean_delta_total": round(float(d["delta_total"].mean()), 3),
        "mean_delta_vs_honest": round(float(d["delta_vs_honest"].mean()), 3),
        "n_positive_delta": int((d["delta_selection"] > 0).sum()),
    }

    # ---- 诚实区间：新旧口径的对比（正文用来说明折分位数不是区间）----
    fold_w = (d["fold_p97.5"] - d["fold_p2.5"]).values
    boot_w = (d["honest_ci_hi"] - d["honest_ci_lo"]).values
    covers_fold = ((d["fold_p2.5"] <= 0.5) & (d["fold_p97.5"] >= 0.5)).sum()
    covers_boot = ((d["honest_ci_lo"] <= 0.5) & (d["honest_ci_hi"] >= 0.5)).sum()
    out["honest_interval"] = {
        "median_width_fold_percentile": round(float(np.median(fold_w)), 3),
        "median_width_patient_bootstrap": round(float(np.median(boot_w)), 3),
        "n_fold_intervals_spanning_at_least_0.9": int((fold_w >= 0.9).sum()),
        "n_cohorts_fold_interval_covers_0.5": int(covers_fold),
        "n_cohorts_bootstrap_CI_covers_0.5": int(covers_boot),
        "note": "fold percentiles are a spread of correlated small-fold scores, not a CI",
    }

    # ---- 分层表 ----
    strata = []
    for lab, m in (("<40", d["minority"] < 40),
                   ("40-99", (d["minority"] >= 40) & (d["minority"] < 100)),
                   (">=100", d["minority"] >= 100)):
        s = d[m]
        strata.append({"stratum": lab, "cohorts": int(len(s)),
                       "mean_delta_selection": round(float(s["delta_selection"].mean()), 2),
                       "mean_honest_ci_width": round(float((s["honest_ci_hi"] - s["honest_ci_lo"]).mean()), 2),
                       "ci_covers_chance": f"{int(((s['honest_ci_lo']<=0.5)&(s['honest_ci_hi']>=0.5)).sum())}/{len(s)}"})
    out["strata_by_minority_events"] = strata

    # ---- 预测器 / 闸门 / RF / R-G / AIS ----
    for key, fname in (("predictor", "reliability_predictor.json"),
                       ("gate", "screening_gate.json"),
                       ("rf_robustness", "rf_robustness.json"),
                       ("dim_channel", "rg_dim_channel.json"),
                       ("ais", "ais_forensic.json")):
        j = load_json(fname)
        if j is not None:
            out[key] = j

    # ---- AIS 置换（嵌套、exact）----
    perm = load_json("permutation_ICC_nested.json") or load_json("permutation_ICC.json")
    if perm:
        out["ais_permutation"] = {k: perm[k] for k in
                                  ("model", "observed_auc", "pvalue", "n_permutations", "d")
                                  if k in perm}

    # ---- AIS 基线阶梯 ----
    bl = RESULTS / "baselines_ICC.csv"
    if bl.exists():
        b = pd.read_csv(bl)
        out["ais_baselines"] = b[["subset", "n_features", "auc_mean"]].to_dict("records")

    # ---- 计算器表 ----
    # round-26：这里此前用的是 **工作点** 那套系数（kappa_fitted / fit_intercept），
    # 但它们拟合在"以队列自身诚实 AUC 为工作点"的 SE 上，而计算器代入的是 SE(0.5)。
    # 那既不是 R2=0.816 的拟合，也不是正文引用的 R2=0.674 的拟合，会平均高估 Delta 约 0.018
    # （所需事件数 234 -> 357）。改用 counts-only 那套，与 reliability_predictor 的计算器同源。
    pj = out.get("predictor")
    if pj:
        # round-27：计算器改为【零截距重拟合】(kappa0 * SE(0.5))，截距被约束为 0。
        _c0 = pj["counts_only_fit (a=0.5; THIS is the calculator's calibration)"]
        kap, icpt = _c0["kappa0"], 0.0

        def events_needed(delta, prev):
            for e in range(5, 30000):
                np_ = max(1, int(0.30 * e)); nn = max(1, int(0.30 * e * (1 - prev) / prev))
                if icpt + kap * hm_se(0.5, np_, nn) <= delta:
                    return e
            return None
        out["calculator_table"] = {
            f"prev={p}": {f"delta<={x}": events_needed(x, p) for x in (0.05, 0.10, 0.15)}
            for p in (0.2, 0.3, 0.4, 0.5)}

    if args.json:
        print(json.dumps(out, indent=2, ensure_ascii=False))
    else:
        def show(o, ind=0):
            pad = "  " * ind
            if isinstance(o, dict):
                for k, v in o.items():
                    if isinstance(v, (dict, list)):
                        print(f"{pad}{k}:"); show(v, ind + 1)
                    else:
                        print(f"{pad}{k}: {v}")
            elif isinstance(o, list):
                for v in o:
                    if isinstance(v, (dict, list)):
                        show(v, ind); print()
                    else:
                        print(f"{pad}- {v}")
            else:
                print(f"{pad}{o}")
        show(out)


if __name__ == "__main__":
    main()
